prodcard_templates: config/prodcard_templates/HNL_LO
prodcard_storage: /eos/user/a/amascell/HNL/prodcards/13.6TeV
gridpack_storage: /eos/user/a/amascell/HNL/gridpacks/13.6TeV
output_storage: /eos/user/a/amascell/HNL/output/Run3
cond_config: config/conditions_Run3.yaml
gen_era: run3
last_step: MINIAOD
eras:
  - Run3Summer22
  - Run3Summer22EE
gen_fragment: MCProd/gen_fragment_emu.py
default:
  type: majorana
  e_mixing: 0
  tau_mixing: 0
  runs: [ '1-100' ]
  events_per_run: 2000
points:
  # - mass: 1
  #   mu_mixing: 0.112
  # - mass: 2
  #   mu_mixing: 0.0135
  - mass: 3
    mu_mixing: 0.00379
  # - mass: 4
  #   mu_mixing: 0.00151
  # - mass: 5
  #   mu_mixing: 0.000746
  # - mass: 6
  #   mu_mixing: 0.000420
